# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: locomotive_plugin_joiner 0.1.9 ruby lib

Gem::Specification.new do |s|
  s.name = "locomotive_plugin_joiner"
  s.version = "0.1.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Markus Roth "]
  s.date = "2014-07-12"
  s.description = "This gem is for everybody wants some extras on logomotiveCMS."
  s.email = "mr@mediatrooper.de"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/locomotive_plugin_joiner.rb",
    "locomotive_plugin_joiner.gemspec",
    "test/helper.rb",
    "test/test_locomotive_plugin_joiner.rb"
  ]
  s.homepage = "http://github.com/joinfield/locomotive_plugin_joiner"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Get extras on logomotiveCMS."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongoid>, ["~> 3.1.5"])
      s.add_runtime_dependency(%q<locomotive_plugins>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<mongoid>, ["~> 3.1.5"])
      s.add_dependency(%q<locomotive_plugins>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<mongoid>, ["~> 3.1.5"])
    s.add_dependency(%q<locomotive_plugins>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

